version: '3.8'

services:
  cancer_classification_api:
    build: .
    container_name: cancer_classification_api
    ports:
      - "8000:8000"
    volumes:
      - ./Dataset:/app/Dataset
      - ./model:/app/model
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 